// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Apikey struct {
	ApiKey      string
	Namespace   string
	Owner       string
	Service     string
	Permissions string
	Payload     []byte
	Expired     pgtype.Bool
	ExpiresAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
